### ISSUE TITLE
normal 

### ISSUE THREAD

**Issue by cv-lab-x** [ingra14m/My-exp-Gaussian#1]
hi，did you visualize the normal map?  or supervise the normal by computing pseudo normal from rendering depth?
looking forward to your reply! @ingra14m

**Comment by ingra14m** [comment]
Hi, It's useless. 

I conducted a test using refnerf because the training set of the refnerf dataset has gt normals. Even though I obtained the following normals and depth, the reflective part is still blurred.
![img_v3_0265_14548b5c-1ddf-4956-8221-3ca5b802baag](https://github.com/ingra14m/Specular-Gaussians/assets/63096187/6ed8fbe8-8cf9-4731-b23a-079206c9fd42)
![8394c91b-9c00-4088-8182-b9c262cada42](https://github.com/ingra14m/Specular-Gaussians/assets/63096187/6a504f16-3d96-4a6a-805e-84dd4e2628f6)

**Comment by cv-lab-x** [comment]
> Hi, It's useless.
> 
> I conducted a test using refnerf because the training set of the refnerf dataset has gt normals. Even though I obtained the following normals, the reflective part is still blurred. ![img_v3_0265_14548b5c-1ddf-4956-8221-3ca5b802baag](https://private-user-images.githubusercontent.com/63096187/291030434-6ed8fbe8-8cf9-4731-b23a-079206c9fd42.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTg2NTgsIm5iZiI6MTcwMjgxODM1OCwicGF0aCI6Ii82MzA5NjE4Ny8yOTEwMzA0MzQtNmVkOGZiZTgtOGNmOS00NzMxLWIyM2EtMDc5MjA2YzlmZDQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEzMDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMGNlOGI3M2VhMWJiZjdkMzNjNmQzNDVlNGQ5NjRhNTAyMDU4YzY2YjE5YzIyMDE1YjljMGMwYTQ5ZDYxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tqz7FzoqMsXVYAYLsu8pKsdBR0Lw2GLw5cG-0RogLg)

thanks for your reply, the result looks different with ''GaussianShader: 3D Gaussian Splatting with Shading Functions for Reflective Surfaces ''.  why is it still  blurred? what do you think.  Is the normal loss supervised by gt normal converge well? or maybe the surface of the objects are not clear enough?
